export const COUNTRIES = [
  { code: "EG", name: "Egypt" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "KW", name: "Kuwait" },
  { code: "QA", name: "Qatar" },
  { code: "BH", name: "Bahrain" },
  { code: "OM", name: "Oman" },
  { code: "JO", name: "Jordan" },
  { code: "LB", name: "Lebanon" },
  { code: "IQ", name: "Iraq" },
  { code: "SY", name: "Syria" },
  { code: "YE", name: "Yemen" },
  { code: "LY", name: "Libya" },
  { code: "TN", name: "Tunisia" },
  { code: "DZ", name: "Algeria" },
  { code: "MA", name: "Morocco" },
  { code: "SD", name: "Sudan" },
  { code: "US", name: "United States" },
  { code: "GB", name: "United Kingdom" },
  { code: "DE", name: "Germany" },
  { code: "FR", name: "France" },
  { code: "IT", name: "Italy" },
  { code: "ES", name: "Spain" },
  { code: "NL", name: "Netherlands" },
  { code: "CH", name: "Switzerland" },
  { code: "SE", name: "Sweden" },
  { code: "NO", name: "Norway" },
  { code: "DK", name: "Denmark" },
  { code: "FI", name: "Finland" },
  { code: "PL", name: "Poland" },
  { code: "RU", name: "Russia" },
  { code: "CN", name: "China" },
  { code: "JP", name: "Japan" },
  { code: "KR", name: "South Korea" },
  { code: "IN", name: "India" },
  { code: "SG", name: "Singapore" },
  { code: "MY", name: "Malaysia" },
  { code: "TH", name: "Thailand" },
  { code: "VN", name: "Vietnam" },
  { code: "PH", name: "Philippines" },
  { code: "ID", name: "Indonesia" },
  { code: "AU", name: "Australia" },
  { code: "NZ", name: "New Zealand" },
  { code: "BR", name: "Brazil" },
  { code: "AR", name: "Argentina" },
  { code: "MX", name: "Mexico" },
  { code: "CA", name: "Canada" },
  { code: "ZA", name: "South Africa" },
  { code: "NG", name: "Nigeria" },
  { code: "KE", name: "Kenya" },
  { code: "TZ", name: "Tanzania" },
  { code: "GH", name: "Ghana" },
  { code: "CO", name: "Colombia" },
  { code: "CL", name: "Chile" },
  { code: "PE", name: "Peru" },
  { code: "EC", name: "Ecuador" },
  { code: "VE", name: "Venezuela" },
  { code: "PT", name: "Portugal" },
  { code: "GR", name: "Greece" },
  { code: "TR", name: "Turkey" },
  { code: "UA", name: "Ukraine" },
  { code: "RO", name: "Romania" },
  { code: "HU", name: "Hungary" },
  { code: "CZ", name: "Czech Republic" },
  { code: "AT", name: "Austria" },
  { code: "BE", name: "Belgium" },
  { code: "IE", name: "Ireland" },
  { code: "IL", name: "Israel" },
];

export const ACTION_FIELDS: Record<string, Array<{
  name: string;
  label: string;
  type: "text" | "date" | "select" | "textarea" | "file" | "boolean" | "number";
  options?: { value: string; label: string }[];
  dependsOn?: { field: string; value: string };
}>> = {
  // TRADEMARK ACTIONS
  "Trademark search": [
    { name: "country", label: "Country", type: "select", options: COUNTRIES.map(c => ({ value: c.code, label: c.name })) },
    { name: "trademark", label: "Trademark", type: "text" },
    { name: "classes", label: "Classes", type: "text" },
    { name: "client", label: "Client", type: "text" },
    { name: "searchDate", label: "Search date", type: "date" },
    { name: "resultReport", label: "Result / Report", type: "textarea" },
  ],
  "Application preparation": [
    { name: "country", label: "Country", type: "select", options: COUNTRIES.map(c => ({ value: c.code, label: c.name })) },
    { name: "trademark", label: "Trademark", type: "text" },
    { name: "applicant", label: "Applicant", type: "text" },
    { name: "classes", label: "Classes", type: "text" },
    { name: "goodsServices", label: "Goods & Services", type: "textarea" },
    { name: "priorityClaim", label: "Priority claim", type: "text" },
    { name: "poaReceived", label: "POA Received", type: "boolean" },
    { name: "poaReceivedDate", label: "POA Received Date", type: "date", dependsOn: { field: "poaReceived", value: "true" } },
    { name: "poaSubmitted", label: "POA Submitted", type: "boolean" },
    { name: "poaSubmittedDate", label: "POA Submitted Date", type: "date", dependsOn: { field: "poaSubmitted", value: "true" } },
    { name: "crReceived", label: "CR Received", type: "boolean" },
    { name: "crReceivedDate", label: "CR Received Date", type: "date", dependsOn: { field: "crReceived", value: "true" } },
    { name: "crSubmitted", label: "CR Submitted", type: "boolean" },
    { name: "crSubmittedDate", label: "CR Submitted Date", type: "date", dependsOn: { field: "crSubmitted", value: "true" } },
  ],
  "Application filing": [
    { name: "trademarkKey", label: "Trademark Key", type: "text" },
    { name: "fileReference", label: "File Reference", type: "text" },
    { name: "trademark", label: "Trademark", type: "text" },
    { name: "device", label: "Device", type: "file" },
    { name: "trademarkStatus", label: "Trademark Status", type: "text" },
    { name: "supervisor", label: "Supervisor", type: "text" },
    { name: "responsibleStaff", label: "Responsible Staff", type: "text" },
    { name: "countryJurisdiction", label: "Country / Jurisdiction", type: "select", options: COUNTRIES.map(c => ({ value: c.code, label: c.name })) },
    { name: "filingSystem", label: "Filing System", type: "select", options: [{ value: "National", label: "National" }, { value: "Madrid", label: "Madrid" }] },
    { name: "applicantName", label: "Applicant Name", type: "text" },
    { name: "applicantAddress", label: "Applicant Address", type: "textarea" },
    { name: "applicantCountry", label: "Applicant Country", type: "select", options: COUNTRIES.map(c => ({ value: c.code, label: c.name })) },
    { name: "legalEntityType", label: "Applicant Legal Entity Type", type: "text" },
    { name: "niceClasses", label: "Nice Class(es)", type: "text" },
    { name: "goodsServicesDescription", label: "Goods & Services Description", type: "textarea" },
    { name: "representation", label: "Representation", type: "file" },
    { name: "applicationNumber", label: "Application Number", type: "text" },
    { name: "applicationDate", label: "Application Date", type: "date" },
    { name: "filingReceipt", label: "Filing Receipt Document", type: "text" },
    { name: "priorityNumber", label: "Priority Number", type: "text" },
    { name: "priorityDate", label: "Priority Date", type: "date" },
    { name: "priorityCountry", label: "Priority Country", type: "select", options: COUNTRIES.map(c => ({ value: c.code, label: c.name })) },
    { name: "registrationNumber", label: "Registration Number", type: "text" },
    { name: "registrationDate", label: "Registration Date", type: "date" },
    { name: "registrationCertificate", label: "Registration Certificate Document", type: "text" },
    { name: "nextRenewalDue", label: "Next Renewal Due", type: "date" },
    { name: "agent", label: "Agent", type: "text" },
    { name: "agentCountry", label: "Agent Country", type: "select", options: COUNTRIES.map(c => ({ value: c.code, label: c.name })) },
    { name: "agentReference", label: "Agent Reference", type: "text" },
    { name: "agentEmail", label: "Agent Email", type: "text" },
  ],
  "Office action response": [
    { name: "country", label: "Country", type: "select", options: COUNTRIES.map(c => ({ value: c.code, label: c.name })) },
    { name: "trademark", label: "Trademark", type: "text" },
    { name: "applicationNumber", label: "Application number", type: "text" },
    { name: "officeActionDate", label: "Office action date", type: "date" },
    { name: "responseDeadline", label: "Response deadline", type: "date" },
    { name: "responseFilingDate", label: "Response filing date", type: "date" },
  ],
  "Publication monitoring": [
    { name: "country", label: "Country", type: "select", options: COUNTRIES.map(c => ({ value: c.code, label: c.name })) },
    { name: "trademark", label: "Trademark", type: "text" },
    { name: "applicationNumber", label: "Application number", type: "text" },
    { name: "publicationDate", label: "Publication date", type: "date" },
    { name: "oppositionDeadline", label: "Opposition deadline", type: "date" },
  ],
  "Opposition filing": [
    { name: "country", label: "Country", type: "select", options: COUNTRIES.map(c => ({ value: c.code, label: c.name })) },
    { name: "opposedTrademark", label: "Opposed trademark", type: "text" },
    { name: "opposedApplicationNumber", label: "Opposed application number", type: "text" },
    { name: "opponent", label: "Opponent", type: "text" },
    { name: "filingDate", label: "Filing date", type: "date" },
    { name: "hearingDate", label: "Hearing Date", type: "date" },
    { name: "decision", label: "Decision", type: "textarea" },
  ],
  "Opposition defense": [
    { name: "country", label: "Country", type: "select", options: COUNTRIES.map(c => ({ value: c.code, label: c.name })) },
    { name: "trademark", label: "Trademark", type: "text" },
    { name: "applicationNumber", label: "Application number", type: "text" },
    { name: "opponent", label: "Opponent", type: "text" },
    { name: "defenseFilingDate", label: "Defense filing date", type: "date" },
    { name: "hearingDate", label: "Hearing Date", type: "date" },
    { name: "decision", label: "Decision", type: "textarea" },
  ],
  "Renewal": [
    { name: "country", label: "Country", type: "select", options: COUNTRIES.map(c => ({ value: c.code, label: c.name })) },
    { name: "trademark", label: "Trademark", type: "text" },
    { name: "registrationNumber", label: "Registration number", type: "text" },
    { name: "owner", label: "Owner", type: "text" },
    { name: "renewalFilingDate", label: "Renewal filing date", type: "date" },
    { name: "certificateIssuanceDate", label: "Certificate issuance date", type: "date" },
    { name: "nextRenewalDue", label: "Next renewal due", type: "date" },
  ],
  "Recordal (assignment / license / change)": [
    { name: "country", label: "Country", type: "select", options: COUNTRIES.map(c => ({ value: c.code, label: c.name })) },
    { name: "trademark", label: "Trademark", type: "text" },
    { name: "applicationRegistrationNumber", label: "Application / Registration number", type: "text" },
    { name: "recordalType", label: "Recordal type", type: "text" },
    { name: "newOwner", label: "New owner / Party", type: "text" },
    { name: "recordalDate", label: "Recordal date", type: "date" },
  ],
  "Coexistence agreement": [
    { name: "trademark", label: "Trademark", type: "text" },
    { name: "country", label: "Country", type: "select", options: COUNTRIES.map(c => ({ value: c.code, label: c.name })) },
    { name: "parties", label: "Parties", type: "text" },
    { name: "agreementDate", label: "Agreement date", type: "date" },
  ],
  "Trademark watch": [
    { name: "trademarkMonitored", label: "Trademark monitored", type: "text" },
    { name: "country", label: "Country", type: "select", options: COUNTRIES.map(c => ({ value: c.code, label: c.name })) },
    { name: "classes", label: "Classes", type: "text" },
    { name: "watchStartDate", label: "Watch start date", type: "date" },
  ],
  "Infringement review": [
    { name: "trademark", label: "Trademark", type: "text" },
    { name: "country", label: "Country", type: "select", options: COUNTRIES.map(c => ({ value: c.code, label: c.name })) },
    { name: "suspectedInfringer", label: "Suspected infringer", type: "text" },
    { name: "reviewDate", label: "Review date", type: "date" },
  ],
  "Cease & desist": [
    { name: "trademark", label: "Trademark", type: "text" },
    { name: "country", label: "Country", type: "select", options: COUNTRIES.map(c => ({ value: c.code, label: c.name })) },
    { name: "recipient", label: "Recipient", type: "text" },
    { name: "letterDate", label: "Letter date", type: "date" },
  ],
  "Customs recordal": [
    { name: "country", label: "Country", type: "select", options: COUNTRIES.map(c => ({ value: c.code, label: c.name })) },
    { name: "trademark", label: "Trademark", type: "text" },
    { name: "registrationNumber", label: "Registration number", type: "text" },
    { name: "filingDate", label: "Filing date", type: "date" },
    { name: "expiryDate", label: "Expiry date", type: "date" },
  ],
  "Cancellation / petition": [
    { name: "country", label: "Country", type: "select", options: COUNTRIES.map(c => ({ value: c.code, label: c.name })) },
    { name: "trademark", label: "Trademark", type: "text" },
    { name: "applicationRegistrationNumber", label: "Application / Registration number", type: "text" },
    { name: "petitionDate", label: "Petition date", type: "date" },
    { name: "hearingDate", label: "Hearing Date", type: "date" },
    { name: "decision", label: "Decision", type: "textarea" },
  ],
  // ENFORCEMENT ACTIONS
  "Complaint": [
    { name: "country", label: "Country", type: "select", options: COUNTRIES.map(c => ({ value: c.code, label: c.name })) },
    { name: "trademark", label: "Trademark", type: "text" },
    { name: "registrationApplicationNumber", label: "Registration / Application number", type: "text" },
    { name: "complainant", label: "Complainant (client)", type: "text" },
    { name: "respondent", label: "Respondent / Infringer", type: "text" },
    { name: "authority", label: "Authority", type: "select", options: [
      { value: "Trademark Office", label: "Trademark Office" },
      { value: "Customs", label: "Customs" },
      { value: "Police", label: "Police" },
      { value: "Online platform", label: "Online platform" }
    ]},
    { name: "complaintType", label: "Complaint type", type: "select", options: [
      { value: "administrative", label: "Administrative" },
      { value: "enforcement", label: "Enforcement" }
    ]},
    { name: "filingDate", label: "Filing date", type: "date" },
    { name: "status", label: "Status", type: "text" },
  ],
  // INDUSTRIAL DESIGN ACTIONS
  "Design search (ID)": [
    { name: "country", label: "Country", type: "select", options: COUNTRIES.map(c => ({ value: c.code, label: c.name })) },
    { name: "designTitle", label: "Design Title", type: "text" },
    { name: "applicant", label: "Applicant", type: "text" },
  ],
  "Filing preparation (ID)": [
    { name: "country", label: "Country", type: "select", options: COUNTRIES.map(c => ({ value: c.code, label: c.name })) },
    { name: "designTitle", label: "Design Title", type: "text" },
    { name: "applicant", label: "Applicant", type: "text" },
    { name: "locarnoClass", label: "Locarno Class", type: "text" },
  ],
  "Application filing (ID)": [
    { name: "country", label: "Country", type: "select", options: COUNTRIES.map(c => ({ value: c.code, label: c.name })) },
    { name: "designTitle", label: "Design Title", type: "text" },
    { name: "applicant", label: "Applicant", type: "text" },
    { name: "applicationNumber", label: "Application Number", type: "text" },
    { name: "applicationDate", label: "Application Date", type: "date" },
    { name: "locarnoClass", label: "Locarno Class", type: "text" },
    { name: "priorityNumber", label: "Priority Number", type: "text" },
    { name: "priorityDate", label: "Priority Date", type: "date" },
    { name: "priorityCountry", label: "Priority Country", type: "select", options: COUNTRIES.map(c => ({ value: c.code, label: c.name })) },
    { name: "registrationNumber", label: "Registration Number", type: "text" },
    { name: "registrationDate", label: "Registration Date", type: "date" },
    { name: "nextRenewalDue", label: "Next Renewal Due", type: "date" },
    { name: "client", label: "Client", type: "text" },
    { name: "agent", label: "Agent", type: "text" },
  ],
  "Office action response (ID)": [
    { name: "country", label: "Country", type: "select", options: COUNTRIES.map(c => ({ value: c.code, label: c.name })) },
    { name: "design", label: "Design", type: "text" },
    { name: "applicationNumber", label: "Application Number", type: "text" },
    { name: "officeActionDate", label: "Office Action Date", type: "date" },
    { name: "responseDeadline", label: "Response Deadline", type: "date" },
    { name: "responseFilingDate", label: "Response Filing Date", type: "date" },
  ],
  "Publication monitoring (ID)": [
    { name: "country", label: "Country", type: "select", options: COUNTRIES.map(c => ({ value: c.code, label: c.name })) },
    { name: "design", label: "Design", type: "text" },
    { name: "applicationNumber", label: "Application Number", type: "text" },
    { name: "publicationDate", label: "Publication Date", type: "date" },
  ],
  "Registration processing (ID)": [
    { name: "country", label: "Country", type: "select", options: COUNTRIES.map(c => ({ value: c.code, label: c.name })) },
    { name: "design", label: "Design", type: "text" },
    { name: "applicationNumber", label: "Application Number", type: "text" },
    { name: "registrationNumber", label: "Registration Number", type: "text" },
    { name: "registrationDate", label: "Registration Date", type: "date" },
  ],
  "Renewal (ID)": [
    { name: "country", label: "Country", type: "select", options: COUNTRIES.map(c => ({ value: c.code, label: c.name })) },
    { name: "design", label: "Design", type: "text" },
    { name: "registrationNumber", label: "Registration Number", type: "text" },
    { name: "owner", label: "Owner", type: "text" },
    { name: "renewalFilingDate", label: "Renewal Filing Date", type: "date" },
    { name: "nextRenewalDue", label: "Next Renewal Due", type: "date" },
  ],
  "Recordal (ID)": [
    { name: "country", label: "Country", type: "select", options: COUNTRIES.map(c => ({ value: c.code, label: c.name })) },
    { name: "design", label: "Design", type: "text" },
    { name: "applicationRegistrationNumber", label: "Registration / Application Number", type: "text" },
    { name: "recordalType", label: "Recordal Type", type: "text" },
    { name: "newOwner", label: "New Owner / Party", type: "text" },
    { name: "recordalDate", label: "Recordal Date", type: "date" },
  ],
  "Design watch (ID)": [
    { name: "country", label: "Country", type: "select", options: COUNTRIES.map(c => ({ value: c.code, label: c.name })) },
    { name: "design", label: "Design", type: "text" },
    { name: "watchStartDate", label: "Watch Start Date", type: "date" },
  ],
  "Infringement assessment (ID)": [
    { name: "design", label: "Design", type: "text" },
    { name: "country", label: "Country", type: "select", options: COUNTRIES.map(c => ({ value: c.code, label: c.name })) },
    { name: "suspectedInfringer", label: "Suspected Infringer", type: "text" },
    { name: "assessmentDate", label: "Assessment Date", type: "date" },
  ],
};